"""The catalog of vendored web-UI fonts and the ``active.css`` generator.

Fonts are a property of the *browser* page (``--ui webgui``/``gui``), not the
TUI — in a real terminal the emulator's own font applies and this package only
persists the preference (see :mod:`webfonts.preference`). Each family lives in
``webui/fonts/<slug>/`` as woff2 files plus its license.

The served page loads a single generated stylesheet, ``fonts/active.css``,
instead of hardcoded ``@font-face`` rules. For the active family it declares
both the family's real name and a ``"Roboto Mono"`` alias — the terminal
renderer in textual-serve's ``js/textual.js`` hardcodes that fontFamily, and an
``@font-face`` with the same name beats any local install during CSS font
matching, so no JS patching is needed. ``__main__._webui_overrides`` writes the
stylesheet at server start; the ``/fonts`` commit rewrites it in place (the
scratch statics dir travels to the app subprocess via ``FONTS_DIR_ENV``), and
aiohttp serves statics from disk per request, so a browser reload applies it.

Families that ship only a Regular cut declare a single face; browsers
synthesize bold/italic from it.
"""

from __future__ import annotations

import os
import tempfile
from dataclasses import dataclass
from pathlib import Path

# Set by ``__main__._webui_overrides`` in the server process; inherited by the
# per-tab app subprocesses (textual-serve copies ``os.environ``). Absent when
# running as a plain TUI, which is how ``/fonts`` knows a reload hint would be
# meaningless.
FONTS_DIR_ENV = "QWOWL35_WEBUI_FONTS_DIR"

DEFAULT_SLUG = "mononoki"


@dataclass(frozen=True)
class FontFile:
    filename: str          # e.g. "MononokiNerdFontMono-Bold.woff2"
    weight: str = "normal"  # "normal" | "bold"
    style: str = "normal"   # "normal" | "italic"


@dataclass(frozen=True)
class FontFamily:
    slug: str        # directory name under webui/fonts/
    label: str       # row text in the /fonts picker
    css_family: str  # @font-face family name (any stable string — we declare it)
    files: tuple[FontFile, ...]
    monospace: bool = True


def _four_cuts(stem: str) -> tuple[FontFile, ...]:
    """The standard Regular/Bold/Italic/BoldItalic quartet of ``<stem>-*.woff2``."""
    return (
        FontFile(f"{stem}-Regular.woff2"),
        FontFile(f"{stem}-Bold.woff2", weight="bold"),
        FontFile(f"{stem}-Italic.woff2", style="italic"),
        FontFile(f"{stem}-BoldItalic.woff2", weight="bold", style="italic"),
    )


# Order here is the order shown in the /fonts picker.
CATALOG: tuple[FontFamily, ...] = (
    FontFamily(
        "mononoki", "Mononoki Nerd Font Mono", "Mononoki Nerd Font Mono",
        _four_cuts("MononokiNerdFontMono"),
    ),
    FontFamily(
        "meslo", "MesloLGM Nerd Font Mono", "MesloLGM Nerd Font Mono",
        _four_cuts("MesloLGMNerdFontMono"),
    ),
    FontFamily(
        "terminus", "Terminess Nerd Font Mono", "Terminess Nerd Font Mono",
        _four_cuts("TerminessNerdFontMono"),
    ),
    FontFamily(
        "gohu", "Gohu uni14 Nerd Font Mono", "GohuFont uni14 Nerd Font Mono",
        (FontFile("GohuFontuni14NerdFontMono-Regular.woff2"),),
    ),
    FontFamily(
        "proggyclean", "ProggyClean Nerd Font Mono", "ProggyClean Nerd Font Mono",
        (FontFile("ProggyCleanNerdFontMono-Regular.woff2"),),
    ),
    FontFamily(
        "vaticanus", "Vaticanus (decorative, not mono)", "Vaticanus",
        (FontFile("Vaticanus-G3yVG.woff2"),),
        monospace=False,
    ),
    FontFamily(
        "pixelpurl", "Pixel Purl (pixel, not mono)", "Pixel Purl",
        (FontFile("PixelPurl.woff2"),),
        monospace=False,
    ),
)


def slugs() -> list[str]:
    return [family.slug for family in CATALOG]


def get(slug: str) -> FontFamily | None:
    return next((family for family in CATALOG if family.slug == slug), None)


def active_css(family: FontFamily) -> str:
    """The ``active.css`` stylesheet text for ``family``.

    URLs are relative to the stylesheet itself (``/static/fonts/active.css`` →
    ``/static/fonts/<slug>/…``): the file is written at runtime, not rendered
    through Jinja, so it cannot use ``{{ config.static.url }}``.
    """
    blocks = []
    for name in (family.css_family, "Roboto Mono"):
        for file in family.files:
            blocks.append(
                "@font-face {\n"
                f'  font-family: "{name}";\n'
                f'  src: url("{family.slug}/{file.filename}") format("woff2");\n'
                f"  font-weight: {file.weight};\n"
                f"  font-style: {file.style};\n"
                "}\n"
            )
    return f"/* generated by qwowl35 /fonts — active family: {family.slug} */\n" + "\n".join(blocks)


def write_active_css(fonts_dir: str | Path, family: FontFamily) -> None:
    """Write ``<fonts_dir>/active.css`` atomically. Best-effort — never raises."""
    try:
        path = Path(fonts_dir) / "active.css"
        # Sibling temp file + atomic rename, so a reload mid-write can never
        # see a half-written stylesheet (same pattern as theme/preference.py).
        fd, tmp = tempfile.mkstemp(dir=str(path.parent), prefix=".active-", suffix=".tmp")
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as f:
                f.write(active_css(family))
            os.replace(tmp, path)
        finally:
            try:
                os.unlink(tmp)
            except OSError:
                pass
    except OSError:
        pass
